/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eduremind;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        stage.setResizable(false);
        stage.setTitle("Edu Remind");
    }

    public static void main(String[] args) {
        launch(args);
    }
}
